# 자동배포 x 수동배포해야함
apiVersion: v1
kind: Service
metadata:
  name: apigateway-service
  namespace: sj-lab
spec:
  selector:
    app: apigateway
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 8100 # test
      nodePort: 30089
  type: NodePort
