apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mapservice-rest.fullname" . }}
  labels:
    app: {{ include "mapservice-rest.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "mapservice-rest.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "mapservice-rest.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.spring.profile | default "prod" }}
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "mapservice-rest.fullname" . }}-config
