apiVersion: v1
kind: Service
metadata:
  name: {{ include "mapservice-rest.fullname" . }}
spec:
  selector:
    app: {{ include "mapservice-rest.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080
  type: {{ .Values.service.type }}
