apiVersion: v1
kind: Service
metadata:
  name: qfieldcloud-app
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: qfieldcloud-app
  ports:
    - port: 8000
      targetPort: 8000