apiVersion: apps/v1
kind: Deployment
metadata:
  name: qfieldcloud-nginx
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qfieldcloud-nginx
  template:
    metadata:
      labels:
        app: qfieldcloud-nginx
    spec:
      containers:
        - name: nginx
          image: {{ .Values.nginx.image }}
          ports:
            - containerPort: 80