apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qfieldcloud-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.storage.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}