apiVersion: v1
kind: PersistentVolume
metadata:
  name: qfield-worker-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual  # values.yaml의 storageClass 설정값과 반드시 일치해야 함
  hostPath:
    path: /home/kuber-volume/qfield-worker