# qfield-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qfield-worker-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /home/kuber-volume/qfield-worker  # 실제 경로 확인 필수