apiVersion: v1
kind: PersistentVolume
metadata:
  name: qfield-worker-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual  # values.yaml의 storageClass와 동일해야 함
  hostPath:
    path: /home/kuber-volume/qfield-worker # 실제 서버 경로