apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qfieldcloud.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qfieldcloud.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.django.secretKey | quote }}
  SALT_KEY: {{ .Values.django.saltKey | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  STORAGE_ACCESS_KEY_ID: {{ .Values.storage.accessKey | quote }}
  STORAGE_SECRET_ACCESS_KEY: {{ .Values.storage.secretKey | quote }}
  EMAIL_HOST_PASSWORD: {{ .Values.email.password | quote }}
