apiVersion: v1
kind: Secret
metadata:
  name: qfieldcloud-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  MINIO_SECRET_KEY: {{ .Values.minio.secretKey | quote }}