apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "discoveryserver.fullname" . }}-config
  namespace: sj-lab
  labels:
    app: {{ include "discoveryserver.name" . }}
data:
  application.yml: |-
{{ .Values.config.applicationYml | indent 4 }}
  application-local.yml: |-
{{ .Values.config.application-local\.yml | indent 4 }}
  application-prod.yml: |-
{{ .Values.config.application-prod\.yml | indent 4 }}