apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "discoveryserver.fullname" . }}
  namespace: sj-lab
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "discoveryserver.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "discoveryserver.name" . }}
      annotations:
        configmap-checksum: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      imagePullSecrets:
{{- range .Values.image.pullSecrets }}
        - name: {{ .name }}
{{- end }}
      containers:
        - name: {{ include "discoveryserver.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.env.springProfile }}
            - name: SPRING_CONFIG_LOCATION
              value: {{ .Values.env.springConfigLocation }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "discoveryserver.fullname" . }}-config