# 해당 파일 배포시에만 gitops
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
  namespace: sj-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
      annotations: # ✅ [추가] 변경 감지를 위한 주석 필드 추가
        configmap-checksum: "REPLACE_WITH_CONFIGMAP_HASH"  # ✅ [추가] configmap 변경 감지용 체크섬
        service-checksum: "REPLACE_WITH_SERVICE_HASH"      # ✅ [추가] service 변경 감지용 체크섬
    spec:
      imagePullSecrets:
        - name: ncp-registry-secret
      containers:
        - name: apigateway
          image: sj-lab-registry.kr.ncr.ntruss.com/sj-lab-apigateway:34
          ports:
            - containerPort: 8100
          volumeMounts:
            - name: config-volume
              mountPath: /config
          env:
            - name: SPRING_CONFIG_LOCATION
              value: "file:/config/"
            - name: SPRING_PROFILES_ACTIVE
              value: prod
      volumes:
        - name: config-volume
          configMap:
            name: apigateway-config
