apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-geoserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geoserver
  template:
    metadata:
      labels:
        app: geoserver
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      {{- if .Values.webXml.enabled }}
      initContainers:
        - name: seed-webxml
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: [ "/bin/sh","-lc" ]
          args:
            - |
              set -e
              SRC="{{ .Values.webXml.mountDir | default "/opt/geoserver/webapps/geoserver/WEB-INF" }}"
              DST="/webinf"
              # 대상 폴더가 비어 있으면 한 번만 복사(씨딩)
              if [ -z "$(ls -A "$DST" 2>/dev/null)" ]; then
                echo "Seeding $DST from $SRC ..."
                mkdir -p "$DST"
                cp -a "$SRC"/* "$DST"/
                chown -R 1000:1000 "$DST" || true
              fi
          volumeMounts:
            - name: webinf
              mountPath: /webinf
      {{- end }}
      containers:
        - name: geoserver
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            # GeoServer가 사용할 데이터 디렉터리 경로 명시
            - name: GEOSERVER_DATA_DIR
              value: {{ .Values.dataDir.mountPath | default "/opt/geoserver_data" | quote }}
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            # 기존 경로(과거 플러그인/스크립트 호환)
            - name: data-dir
              mountPath: /opt/geoserver/data_dir
            # GeoServer가 실제 로그에 표시하는 경로도 함께 마운트
            - name: data-dir
              mountPath: {{ .Values.dataDir.mountPath | default "/opt/geoserver_data" | quote }}
      volumes:
        {{- if .Values.webXml.enabled }}
        - name: webinf
          {{- if .Values.webXml.hostPath.enabled }}
          hostPath:
            path: {{ .Values.webXml.hostPath.path | quote }}
            type: DirectoryOrCreate
          {{- else if .Values.webXml.pvc.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.webXml.pvc.claimName | quote }}
          {{- end }}
        {{- end }}
        - name: data-dir
{{- if .Values.hostPath.enabled }}
          hostPath:
            path: {{ .Values.hostPath.path }}
            type: DirectoryOrCreate
{{- else }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-geoserver-pvc
{{- end }}
