apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-geoserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geoserver
  template:
    metadata:
      labels:
        app: geoserver
    spec:
      containers:
        - name: geoserver
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            # GeoServer가 사용할 데이터 디렉터리 경로 명시
            - name: GEOSERVER_DATA_DIR
              value: {{ .Values.dataDir.mountPath | default "/opt/geoserver_data" | quote }}
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            # 기존 경로(과거 플러그인/스크립트 호환)
            - name: data-dir
              mountPath: /opt/geoserver
            # GeoServer가 실제 로그에 표시하는 경로도 함께 마운트
            - name: data-dir
              mountPath: {{ .Values.dataDir.mountPath | default "/opt/geoserver_data" | quote }}
      volumes:
        - name: data-dir
{{- if .Values.hostPath.enabled }}
          hostPath:
            path: {{ .Values.hostPath.path }}
            type: DirectoryOrCreate
{{- else }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-geoserver-pvc
{{- end }}
