apiVersion: v1
kind: Service
metadata:
  name: {{ include "jenkins.fullname" . }}-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "jenkins.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.httpPort }}
      nodePort: {{ .Values.service.httpNodePort }}
    - name: agent
      port: {{ .Values.service.agentPort }}
      targetPort: {{ .Values.service.agentPort }}
      nodePort: {{ .Values.service.agentNodePort }}