{{- if .Values.persistence.createStorageClass -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.persistence.storageClass }}
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: {{ .Values.persistence.reclaimPolicy | default "Retain" }}
{{- end }}