apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: sj-lab
  annotations:
    checksum/nginx-conf: {{ .Files.Get "files/nginx.conf" | sha256sum }}
    checksum/nginx-set-conf: {{ .Files.Get "files/nginx-set.conf" | sha256sum }}
data:
  nginx.conf: |-
{{ .Files.Get "files/nginx.conf" | indent 4 }}
  nginx-set.conf: |-
{{ .Files.Get "files/nginx-set.conf" | indent 4 }}