apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: sj-lab
data:
  nginx.conf: |
    {{ .Files.Get "config/nginx.conf" | indent 4 }}
  nginx-set.conf: |
    {{ .Files.Get "config/nginx-set.conf" | indent 4 }}
