apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sj-lab-webserver.fullname" . }}
  labels:
    app: {{ include "sj-lab-webserver.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "sj-lab-webserver.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "sj-lab-webserver.name" . }}
    spec:
      containers:
        - name: nginx
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
              - containerPort: 80
          volumeMounts:
            - name: web-content
              mountPath: /home/www
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/nginx-set.conf
              subPath: nginx-set.conf
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: certs
              mountPath: /etc/letsencrypt
            - name: error-pages
              mountPath: /home
      volumes:
        - name: web-content
          hostPath:
            path: {{ .Values.volumes.webContent }}
            type: Directory
        - name: nginx-config
          configMap:
            name: {{ .Values.configMapName }}
        - name: certs
          hostPath:
            path: {{ .Values.volumes.certs }}
            type: Directory
        - name: error-pages
          hostPath:
            path: {{ .Values.volumes.errorPages }}
            type: Directory
