apiVersion: v1
kind: Service
metadata:
  name: {{ include "sj-lab-webserver.fullname" . }}-service
  namespace: sj-lab
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "sj-lab-webserver.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}