apiVersion: v1
kind: ConfigMap
metadata:
  name: discoveryserver-config
  namespace: sj-lab
data:
  application.yml: |
    server:
      port: 8761
      servlet:
        context-path: /
    spring:
      application:
        name: discoveryservice
      profiles:
        active: prod
    management:
      endpoints:
        web:
          exposure:
            include: "*"
      endpoint:
        health:
          show-details: always
  application-local.yml: |
    eureka:
      client:
        register-with-eureka: false
        fetch-registry: false
        service-url:
          defaultZone: http://localhost:8761/eureka
  application-prod.yml: |
    eureka:
      client:
        register-with-eureka: false
        fetch-registry: false
        service-url:
          defaultZone: https://eureka.sj-lab.co.kr/eureka
