apiVersion: v1
kind: Service
metadata:
  name: discoveryserver
  namespace: sj-lab
spec:
  selector:
    app: discoveryserver
  ports:
    - port: 8761
      targetPort: 8761
      nodePort: 30087
  type: NodePort
