apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qfieldcloud.fullname" . }}-app
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qfieldcloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
  {{- with .Values.app.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      {{- include "qfieldcloud.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: app
  template:
    metadata:
      labels:
        {{- include "qfieldcloud.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: app
    spec:
      serviceAccountName: {{ include "qfieldcloud.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: app
          image: "{{ .Values.image.app.repository }}:{{ .Values.image.app.tag }}"
          imagePullPolicy: {{ .Values.image.app.pullPolicy }}
          command:
            - gunicorn
            - qfieldcloud.wsgi:application
            - --bind
            - 0.0.0.0:8000
            - --timeout
            - $(GUNICORN_TIMEOUT_S)
            - --max-requests
            - $(GUNICORN_MAX_REQUESTS)
            - --workers
            - $(GUNICORN_WORKERS)
            - --threads
            - $(GUNICORN_THREADS)
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            {{- include "qfieldcloud.djangoEnv" . | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /api/v1/status/
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /api/v1/status/
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 3
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          volumeMounts:
            - name: static
              mountPath: /usr/src/app/staticfiles
            - name: media
              mountPath: /usr/src/app/mediafiles
      {{- with .Values.app.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: static
          {{- if .Values.persistence.static.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.static.existingClaim }}
          {{- else if .Values.persistence.static.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "qfieldcloud.fullname" . }}-static
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: media
          {{- if .Values.persistence.media.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.media.existingClaim }}
          {{- else if .Values.persistence.media.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "qfieldcloud.fullname" . }}-media
          {{- else }}
          emptyDir: {}
          {{- end }}
