replicaCount: 1

image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

config:
  nginxConf: |
    # 여기에 nginx.conf 내용 붙여넣기
  nginxSetConf: |
    # 여기에 nginx-set.conf 내용 붙여넣기

volumes:
  webContent: /home/kuber-volume/sj-lab-webserver/html
  certs: /home/kuber-set/sj-lab-webserver/certs/letsencrypt
  errorPages: /home/kuber-set/sj-lab-webserver/error-pages

ingress:
  enabled: true
  host: www.sj-lab.co.kr
