apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgresql.fullname" . }}
spec:
  replicas: 1
  ## [변경 1] hostPath 단일 디렉토리 파일 락 충돌 방지를 위해 Recreate 전략 추가
  strategy:
    type: Recreate
  selector:
    matchLabels:
      ## [변경 2] 기존 'postgresql.name' -> 'postgresql.fullname'으로 변경 (라벨 중복 방지 핵심)
      app: {{ include "postgresql.fullname" . }}
  template:
    metadata:
      labels:
        ## [변경 3] Pod 라벨도 fullname으로 일치시킴
        app: {{ include "postgresql.fullname" . }}
    spec:
      containers:
        - name: postgresql
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.auth.database | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.auth.username | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.auth.password | quote }}
            - name: TZ
              value: "Asia/Seoul"
          volumeMounts:
            - name: {{ .Values.volume.name }}
              mountPath: {{ .Values.volume.mountPath }}
      volumes:
        - name: {{ .Values.volume.name }}
          hostPath:
            path: {{ .Values.volume.hostPath | quote }}
            type: DirectoryOrCreate