apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.fullname" . }}
spec:
  type: NodePort
  selector:
    ## [변경 4] 기존 'postgresql.name' -> 'postgresql.fullname'으로 변경
    ## (qfield 파드가 아닌 본인 deployment 파드만 1:1로 정확하게 타깃팅)
    app: {{ include "postgresql.fullname" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}