image:
  repository: sj-lab-registry.kr.ncr.ntruss.com/mapservice-rest
  tag: 29
  pullSecret: ncp-registry-secret

spring:
  profile: prod

service:
  type: ClusterIP
  port: 8080

env:
  springProfile: prod
  springConfigLocation: "classpath:/,file:/app/config/"

fullnameOverride: mapservice-rest