{{- if .Values.cronjob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "qfieldcloud.fullname" . }}-runcrons
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qfieldcloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: cronjob
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 60
      template:
        metadata:
          labels:
            {{- include "qfieldcloud.selectorLabels" . | nindent 12 }}
            app.kubernetes.io/component: cronjob
        spec:
          restartPolicy: OnFailure
          serviceAccountName: {{ include "qfieldcloud.serviceAccountName" . }}
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: runcrons
              image: "{{ .Values.image.app.repository }}:{{ .Values.image.app.tag }}"
              imagePullPolicy: {{ .Values.image.app.pullPolicy }}
              command:
                {{- toYaml .Values.cronjob.command | nindent 16 }}
              env:
                {{- include "qfieldcloud.djangoEnv" . | nindent 16 }}
              volumeMounts:
                - name: static
                  mountPath: /usr/src/app/staticfiles
                - name: media
                  mountPath: /usr/src/app/mediafiles
          volumes:
            - name: static
              {{- if .Values.persistence.static.existingClaim }}
              persistentVolumeClaim:
                claimName: {{ .Values.persistence.static.existingClaim }}
              {{- else if .Values.persistence.static.enabled }}
              persistentVolumeClaim:
                claimName: {{ include "qfieldcloud.fullname" . }}-static
              {{- else }}
              emptyDir: {}
              {{- end }}
            - name: media
              {{- if .Values.persistence.media.existingClaim }}
              persistentVolumeClaim:
                claimName: {{ .Values.persistence.media.existingClaim }}
              {{- else if .Values.persistence.media.enabled }}
              persistentVolumeClaim:
                claimName: {{ include "qfieldcloud.fullname" . }}-media
              {{- else }}
              emptyDir: {}
              {{- end }}
{{- end }}
