apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qfieldcloud.fullname" . }}-nginx
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qfieldcloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
spec:
  replicas: {{ .Values.nginx.replicas }}
  selector:
    matchLabels:
      {{- include "qfieldcloud.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: nginx
  template:
    metadata:
      labels:
        {{- include "qfieldcloud.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: nginx
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/nginx/configmap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ include "qfieldcloud.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: nginx
          image: "{{ .Values.image.nginx.repository }}:{{ .Values.image.nginx.tag }}"
          imagePullPolicy: {{ .Values.image.nginx.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            {{- toYaml .Values.nginx.resources | nindent 12 }}
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: static
              mountPath: /var/www/html/staticfiles
              readOnly: true
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "qfieldcloud.fullname" . }}-nginx-config
        - name: static
          {{- if .Values.persistence.static.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.static.existingClaim }}
          {{- else if .Values.persistence.static.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "qfieldcloud.fullname" . }}-static
          {{- else }}
          emptyDir: {}
          {{- end }}
