apiVersion: v1
kind: Service
metadata:
  name: {{ include "qfieldcloud.fullname" . }}-nginx
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qfieldcloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "qfieldcloud.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
