auth:
  database: sjlab
  username: stylealist
  password: !@xogml159
  postgresPassword: !@xogml159

image:
  repository: postgres
  tag: "17.5-alpine"

fullnameOverride: "postgresql"

service:
  port: 5432
  nodePort: 30017

volume:
  enabled: true
  name: postgresql-storage
  mountPath: /bitnami/postgresql
  hostPath: /home/kuber-volume/postgres  # <- CHANGE THIS to your desired local path
