auth:
  database: geoserverdb
  username: geoserver
  password: geoserverpw
  postgresPassword: postgres

image:
  repository: bitnami/postgresql
  tag: "17.5.0-debian-11-r0"

fullnameOverride: "postgresql"

service:
  port: 5432
  nodePort: 30017

volume:
  enabled: true
  name: postgresql-storage
  mountPath: /bitnami/postgresql
  hostPath: /home/kuber-volume/postgres  # <- CHANGE THIS to your desired local path
