apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "apigateway.fullname" . }}-config
  namespace: sj-lab
  labels:
    app: {{ include "apigateway.name" . }}
data:
  application-prod.yml: |-
{{ .Files.Get "files/application-prod.yml" | indent 4 }}
